/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication.smartcity;

import javax.swing.JFrame;
import java.sql.*;
/**
 *
 * @author vivek
 */
public class AddDetails extends javax.swing.JFrame {

    /**
     * Creates new form Layout
     */
    public AddDetails() {
        initComponents();
        setTitle("Admin Login");
        setSize(1000,600);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        infraType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        School = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputText1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputText2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputText3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputText4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputText5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputText6 = new javax.swing.JTextField();
        Hospital = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        hname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        harea = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hbudget = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        hdistrict = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        hstate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        hpincode = new javax.swing.JTextField();
        Roads = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        rname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        rarea = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        rbudget = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        rdistrict = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        rstate = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        rpincode = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        infraType.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        infraType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "School / College", "Hospital", "Roads" }));
        infraType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infraTypeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cochin", 1, 16)); // NOI18N
        jLabel8.setText("Infrastructure Type");

        Add.setBackground(new java.awt.Color(0, 153, 255));
        Add.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        Add.setText("Add Details");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(153, 153, 153));
        backButton.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon("/Users/vivek/NetBeansProjects/SmartCity/src/main/java/images/go back.png")); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(650, 250));
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        School.setBackground(new java.awt.Color(153, 153, 153));
        School.setMaximumSize(new java.awt.Dimension(1000, 600));
        School.setPreferredSize(new java.awt.Dimension(650, 280));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("SCHOOL/COLLEGE NAME  :");

        inputText1.setBackground(new java.awt.Color(204, 204, 204));
        inputText1.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        inputText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputText1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel2.setText("SCHOOL / COLLEGE CODE :");

        inputText2.setBackground(new java.awt.Color(204, 204, 204));
        inputText2.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        inputText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputText2ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel3.setText("AREA IN SQ.METERS :");

        inputText3.setBackground(new java.awt.Color(204, 204, 204));
        inputText3.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel4.setText("ADDRESS :");

        inputText4.setBackground(new java.awt.Color(204, 204, 204));
        inputText4.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        inputText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputText4ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel6.setText("DISTRICT :");

        inputText5.setBackground(new java.awt.Color(204, 204, 204));
        inputText5.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        inputText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputText5ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel7.setText("STATE :");

        inputText6.setBackground(new java.awt.Color(204, 204, 204));
        inputText6.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N

        javax.swing.GroupLayout SchoolLayout = new javax.swing.GroupLayout(School);
        School.setLayout(SchoolLayout);
        SchoolLayout.setHorizontalGroup(
            SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SchoolLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(inputText1)
                        .addComponent(inputText2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputText6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inputText5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(inputText4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(inputText3)))
                .addGap(863, 863, 863))
        );
        SchoolLayout.setVerticalGroup(
            SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SchoolLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputText1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(inputText2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(inputText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SchoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SchoolLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(SchoolLayout.createSequentialGroup()
                        .addComponent(inputText4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(inputText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputText6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        jPanel2.add(School);
        School.setVisible(false);

        Hospital.setBackground(new java.awt.Color(153, 153, 153));
        Hospital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Hospital.setPreferredSize(new java.awt.Dimension(650, 250));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel9.setText("HOSPITAL NAME :");

        hname.setBackground(new java.awt.Color(204, 204, 204));
        hname.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        hname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hnameActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel10.setText("AREA IN SQ.METERS :");

        harea.setBackground(new java.awt.Color(204, 204, 204));
        harea.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel11.setText(" BUDGET :");

        hbudget.setBackground(new java.awt.Color(204, 204, 204));
        hbudget.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        hbudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbudgetActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(153, 153, 153));
        jLabel13.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel13.setText("DISTRICT :");

        hdistrict.setBackground(new java.awt.Color(204, 204, 204));
        hdistrict.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        hdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdistrictActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(153, 153, 153));
        jLabel14.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel14.setText("STATE :");

        hstate.setBackground(new java.awt.Color(204, 204, 204));
        hstate.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N

        jLabel15.setBackground(new java.awt.Color(153, 153, 153));
        jLabel15.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel15.setText("PIN CODE :");

        hpincode.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout HospitalLayout = new javax.swing.GroupLayout(Hospital);
        Hospital.setLayout(HospitalLayout);
        HospitalLayout.setHorizontalGroup(
            HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospitalLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(harea)
                    .addComponent(hname)
                    .addComponent(hbudget)
                    .addComponent(hdistrict)
                    .addComponent(hstate)
                    .addComponent(hpincode, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        HospitalLayout.setVerticalGroup(
            HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospitalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HospitalLayout.createSequentialGroup()
                        .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(hname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10))
                    .addGroup(HospitalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(harea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HospitalLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(hbudget, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpincode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jPanel2.add(Hospital);
        Hospital.setVisible(false);

        Roads.setBackground(new java.awt.Color(153, 153, 153));
        Roads.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Roads.setPreferredSize(new java.awt.Dimension(650, 250));

        jLabel12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel12.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel12.setText("Location");

        rname.setBackground(new java.awt.Color(204, 204, 204));
        rname.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        rname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnameActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(153, 153, 153));
        jLabel16.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel16.setText("AREA IN SQ.METERS :");

        rarea.setBackground(new java.awt.Color(204, 204, 204));
        rarea.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N

        jLabel17.setBackground(new java.awt.Color(153, 153, 153));
        jLabel17.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel17.setText(" BUDGET :");

        rbudget.setBackground(new java.awt.Color(204, 204, 204));
        rbudget.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        rbudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbudgetActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(153, 153, 153));
        jLabel18.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel18.setText("DISTRICT :");

        rdistrict.setBackground(new java.awt.Color(204, 204, 204));
        rdistrict.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N
        rdistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdistrictActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(153, 153, 153));
        jLabel19.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel19.setText("STATE :");

        rstate.setBackground(new java.awt.Color(204, 204, 204));
        rstate.setFont(new java.awt.Font("Cochin", 0, 18)); // NOI18N

        jLabel20.setBackground(new java.awt.Color(153, 153, 153));
        jLabel20.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel20.setText("PIN CODE :");

        rpincode.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout RoadsLayout = new javax.swing.GroupLayout(Roads);
        Roads.setLayout(RoadsLayout);
        RoadsLayout.setHorizontalGroup(
            RoadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoadsLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(RoadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(RoadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rarea)
                    .addComponent(rname)
                    .addComponent(rbudget)
                    .addComponent(rdistrict)
                    .addComponent(rstate)
                    .addComponent(rpincode, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        RoadsLayout.setVerticalGroup(
            RoadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoadsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(RoadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(RoadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(rarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RoadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbudget, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(RoadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RoadsLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(rdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RoadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rstate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(RoadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rpincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jPanel2.add(Roads);
        Roads.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(63, 63, 63)
                        .addComponent(infraType, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Add)
                        .addGap(381, 381, 381)
                        .addComponent(backButton)
                        .addGap(40, 40, 40))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infraType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Add.setVisible(false);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        img.setIcon(new javax.swing.ImageIcon("/Users/vivek/NetBeansProjects/SmartCity/src/main/java/images/icons8-add-properties-100.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        jLabel5.setText("Add Details");

        Name.setText("Name");

        user.setText("user");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(112, 112, 112)
                .addComponent(img)
                .addGap(130, 130, 130))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(Name)
                                .addGap(18, 18, 18)
                                .addComponent(user)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        //Name.setVisible(false);
        //user.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputText1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_inputText1ActionPerformed

    private void inputText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputText2ActionPerformed

    private void inputText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputText4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputText4ActionPerformed

    private void inputText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputText5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputText5ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        PreparedStatement pst=null;
        String selected=infraType.getSelectedItem().toString();
        if(selected.equalsIgnoreCase("school / college"))
        {
            String sname=inputText1.getText();
            String scode=inputText2.getText();
            String area=inputText3.getText();
            String address=inputText4.getText();
            String district=inputText5.getText();
            String state=inputText6.getText();
            try
            {
                String url="jdbc:mysql://localhost:3306/SmartCity";
                String usern="root";
                String pwd="";
                con=DriverManager.getConnection(url,usern,pwd);
                if(con!=null)
                {
                    String query="insert into school (school_name,school_code,area,address,district,state) values(?,?,?,?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(1,sname);
                    pst.setString(2,scode);
                    pst.setString(3,area);
                    pst.setString(4,address);
                    pst.setString(5,district);
                    pst.setString(6,state);
                    pst.executeUpdate();
                    String query1="insert into details(name,infra_type,district) values(?,?,?)";
                    pst=con.prepareStatement(query1);
                    pst.setString(1,sname);
                    pst.setString(2, "School");
                    pst.setString(3,district);
                    pst.executeUpdate();
                }
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
        if(selected.equalsIgnoreCase("hospital"))
        {
            String name=hname.getText();
            String area=harea.getText();
            String budget=hbudget.getText();
            String district=hdistrict.getText();
            String state=hstate.getText();
            String pin=hpincode.getText();
            try
            {
                String url="jdbc:mysql://localhost:3306/SmartCity";
                String usern="root";
                String pwd="";
                con=DriverManager.getConnection(url,usern,pwd);
                if(con!=null)
                {
                    String query="insert into hospital (hospital_name,area,budget,district,state,pin_code) values(?,?,?,?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(1,name);
                    pst.setString(2,area);
                    pst.setString(3,budget);
                    pst.setString(4,district);
                    pst.setString(5,state);
                    pst.setString(6,pin);
                    pst.executeUpdate();
                    String query1="insert into details(name,infra_type,district) values(?,?,?)";
                    pst=con.prepareStatement(query1);
                    pst.setString(1,name);
                    pst.setString(2, "Hospital");
                    pst.setString(3,district);
                    pst.executeUpdate();
                }
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
        if(selected.equalsIgnoreCase("roads"))
        {
            String name=rname.getText();
            String area=rarea.getText();
            String budget=rbudget.getText();
            String district=rdistrict.getText();
            String state=rstate.getText();
            String pin=rpincode.getText();
            try
            {
                String url="jdbc:mysql://localhost:3306/SmartCity";
                String usern="root";
                String pwd="";
                con=DriverManager.getConnection(url,usern,pwd);
                if(con!=null)
                {
                    String query="insert into roads (location,area,budget,district,state,pin_code) values(?,?,?,?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(1,name);
                    pst.setString(2,area);
                    pst.setString(3,budget);
                    pst.setString(4,district);
                    pst.setString(5,state);
                    pst.setString(6,pin);
                    pst.executeUpdate();
                    String query1="insert into details(name,infra_type,district) values(?,?,?)";
                    pst=con.prepareStatement(query1);
                    pst.setString(1,name);
                    pst.setString(2, "Roads");
                    pst.setString(3,district);
                    pst.executeUpdate();
                }
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_AddActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        String user1=Name.getText();
        String strusertype=user.getText();
        User usr=new User();
        usr.setUser(user1);
        usr.setUserType(strusertype);
        usr.fillPanel(strusertype);
        usr.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void infraTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infraTypeActionPerformed
        // TODO add your handling code here:
        String selected=infraType.getSelectedItem().toString();
        if(selected.equalsIgnoreCase("school / college"))
        {
            School.setVisible(true);
            Hospital.setVisible(false);
            Roads.setVisible(false);
            Add.setVisible(true);
        }
        else if(selected.equalsIgnoreCase("hospital"))
        {
            School.setVisible(false);
            Hospital.setVisible(true);
            Roads.setVisible(false);
            Add.setVisible(true);
        }
        else if(selected.equalsIgnoreCase("roads"))
        {
            School.setVisible(false);
            Hospital.setVisible(false);
            Roads.setVisible(true);
            Add.setVisible(true);
        }
        else
        {
            School.setVisible(false);
            Hospital.setVisible(false);
            Roads.setVisible(false);
        }
    }//GEN-LAST:event_infraTypeActionPerformed

    private void hnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hnameActionPerformed

    private void hbudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hbudgetActionPerformed

    private void hdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hdistrictActionPerformed

    private void rnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnameActionPerformed

    private void rbudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbudgetActionPerformed

    private void rdistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdistrictActionPerformed

    public void setUser(String user) 
    {
        this.Name.setText(user);
    }
    public void setUserType(String type)
    {
        this.user.setText(type);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JPanel Hospital;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel Roads;
    private javax.swing.JPanel School;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField harea;
    private javax.swing.JTextField hbudget;
    private javax.swing.JTextField hdistrict;
    private javax.swing.JTextField hname;
    private javax.swing.JTextField hpincode;
    private javax.swing.JTextField hstate;
    private javax.swing.JLabel img;
    private javax.swing.JComboBox<String> infraType;
    private javax.swing.JTextField inputText1;
    private javax.swing.JTextField inputText2;
    private javax.swing.JTextField inputText3;
    private javax.swing.JTextField inputText4;
    private javax.swing.JTextField inputText5;
    private javax.swing.JTextField inputText6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField rarea;
    private javax.swing.JTextField rbudget;
    private javax.swing.JTextField rdistrict;
    private javax.swing.JTextField rname;
    private javax.swing.JTextField rpincode;
    private javax.swing.JTextField rstate;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
