/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication.smartcity;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author vivek
 */
public class addUser extends javax.swing.JFrame {

    /**
     * Creates new form addUser
     */
    public addUser() {
        initComponents();
        setTitle("Add User");
        setSize(1000,600);
        
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        userDesignation = new javax.swing.JLabel();
        userType = new javax.swing.JComboBox<>();
        userText = new javax.swing.JLabel();
        inputText = new javax.swing.JTextField();
        userName = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        userDistrict = new javax.swing.JLabel();
        inputDistrict = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon("/Users/vivek/NetBeansProjects/SmartCity/src/main/java/images/go back.png")); // NOI18N
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 153, 255));
        btnAdd.setFont(new java.awt.Font("Cochin", 1, 30)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        userDesignation.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        userDesignation.setText("Designation");

        userType.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Principal", "Contractor", "MLA", "CM" }));
        userType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeActionPerformed(evt);
            }
        });

        userText.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        userText.setText("School");

        inputText.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N

        userName.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        userName.setText("Name");

        inputName.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N

        userDistrict.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        userDistrict.setText("District");

        inputDistrict.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        inputDistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDistrictActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(userDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputText)
                    .addComponent(userType, 0, 170, Short.MAX_VALUE)
                    .addComponent(inputName)
                    .addComponent(inputDistrict))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGap(115, 115, 115))
        );

        userText.setVisible(false);
        inputText.setVisible(false);
        userName.setVisible(false);
        inputName.setVisible(false);
        userDistrict.setVisible(false);
        inputDistrict.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        img.setIcon(new javax.swing.ImageIcon("/Users/vivek/NetBeansProjects/SmartCity/src/main/java/images/add user big.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        jLabel5.setText("Add User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        AdminPage adminpage=new AdminPage();
        adminpage.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name=inputName.getText();
        String txt=inputText.getText();
        String district=inputDistrict.getText();
        String selectedValue=userType.getSelectedItem().toString();
        Connection con=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        try
        {
            String url="jdbc:mysql://localhost:3306/SmartCity";
            String usern="root";
            String pwd="";
            con=DriverManager.getConnection(url,usern,pwd);
            if(con!=null)
            {
                if(selectedValue.equals("Principal"))
                {
                    String query="insert into principal(name,password,district,school) values(?,?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(1,name);
                    pst.setString(2,name+"123");
                    pst.setString(3, district);
                    pst.setString(4, txt);
                    pst.executeUpdate();
                    String query1="insert into login(username,password,usertype) values(?,?,?)";
                    pst=con.prepareStatement(query1);
                    pst.setString(1,name);
                    pst.setString(2,name+"123");
                    pst.setString(3, selectedValue);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "User Added Successfully!");
                    AdminPage adminpage= new AdminPage();
                    adminpage.setVisible(true);
                    dispose();
                }
                if(selectedValue.equals("Contractor"))
                {
                    String query="insert into contractor(name,password,district,company_name) values(?,?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(1,name);
                    pst.setString(2,name+"123");
                    pst.setString(3, district);
                    pst.setString(4, txt);
                    pst.executeUpdate();
                    String query1="insert into login(username,password,usertype) values(?,?,?)";
                    pst=con.prepareStatement(query1);
                    pst.setString(1,name);
                    pst.setString(2,name+"123");
                    pst.setString(3, selectedValue);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "User Added Successfully!");
                    AdminPage adminpage= new AdminPage();
                    adminpage.setVisible(true);
                    dispose();
                }
                if(selectedValue.equals("MLA"))
                {
                    String query="insert into MLA(name,password,district,state) values(?,?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(1,name);
                    pst.setString(2,name+"123");
                    pst.setString(3, district);
                    pst.setString(4, txt);
                    pst.executeUpdate();
                    String query1="insert into login(username,password,usertype) values(?,?,?)";
                    pst=con.prepareStatement(query1);
                    pst.setString(1,name);
                    pst.setString(2,name+"123");
                    pst.setString(3, selectedValue);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "User Added Successfully");
                    AdminPage adminpage= new AdminPage();
                    adminpage.setVisible(true);
                    dispose();
                }
                if(selectedValue.equals("CM"))
                {
                    String query="insert into CM(name,password,state) values(?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(1,name);
                    pst.setString(2,name+"123");
                    pst.setString(3, txt);
                    pst.executeUpdate();
                    String query1="insert into login(username,password,usertype) values(?,?,?)";
                    pst=con.prepareStatement(query1);
                    pst.setString(1,name);
                    pst.setString(2,name+"123");
                    pst.setString(3, selectedValue);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "User Added Successfully!");
                    AdminPage adminpage= new AdminPage();
                    adminpage.setVisible(true);
                    dispose();
                }
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void userTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeActionPerformed
        // TODO add your handling code here:
        String selectedValue=userType.getSelectedItem().toString();
        if(selectedValue.equals("Select"))
        {
            userName.setVisible(false);
            inputName.setVisible(false);
            userDistrict.setVisible(false);
            inputDistrict.setVisible(false);
            inputText.setVisible(false);
            userText.setVisible(false);
        }
        else if(selectedValue.equals("Principal"))
        {
            userName.setVisible(true);
            inputName.setVisible(true);
            userDistrict.setVisible(true);
            inputDistrict.setVisible(true);
            inputText.setVisible(true);
            userText.setVisible(true);
            userText.setText("School");
        }
        else if(selectedValue.equals("Contractor"))
        {
            userName.setVisible(true);
            inputName.setVisible(true);
            userDistrict.setVisible(true);
            inputDistrict.setVisible(true);
            userText.setText("Company Name");
            inputText.setVisible(true);
            userText.setVisible(true);
        }
        else if(selectedValue.equals("MLA"))
        {
            userName.setVisible(true);
            inputName.setVisible(true);
            userDistrict.setVisible(true);
            inputDistrict.setVisible(true);
            userText.setText("State");
            inputText.setVisible(true);
            userText.setVisible(true);
        }
        else
        {
            userName.setVisible(true);
            inputName.setVisible(true);
            userDistrict.setVisible(false);
            inputDistrict.setVisible(false);
            userText.setVisible(true);
            inputText.setVisible(true);
            userText.setText("State");
        }
    }//GEN-LAST:event_userTypeActionPerformed

    private void inputDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDistrictActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel img;
    private javax.swing.JTextField inputDistrict;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputText;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel userDesignation;
    private javax.swing.JLabel userDistrict;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userText;
    private javax.swing.JComboBox<String> userType;
    // End of variables declaration//GEN-END:variables
}
