/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication.smartcity;

import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author bhaskar patidar
 */
public class UpdateUser extends javax.swing.JFrame {
    /**
     * Creates new form AddUser
     */
    public UpdateUser() {
        initComponents();
          setTitle("Add User");
        setSize(1000,600);
        
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        userDesignation = new javax.swing.JLabel();
        userType = new javax.swing.JComboBox<>();
        userText = new javax.swing.JLabel();
        inputText = new javax.swing.JTextField();
        userName = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        userDistrict = new javax.swing.JLabel();
        inputDistrict = new javax.swing.JTextField();
        userText1 = new javax.swing.JLabel();
        userText2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon("/Users/vivek/NetBeansProjects/SmartCity/src/main/java/images/go back.png")); // NOI18N
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 153, 255));
        btnAdd.setFont(new java.awt.Font("Cochin", 1, 30)); // NOI18N
        btnAdd.setText("Update");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        userDesignation.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        userDesignation.setText("Name");

        userType.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        userType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeActionPerformed(evt);
            }
        });

        userText.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        userText.setText("School");

        inputText.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N

        userName.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        userName.setText("Updated Name");

        inputName.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N

        userDistrict.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        userDistrict.setText("District");

        inputDistrict.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        inputDistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDistrictActionPerformed(evt);
            }
        });

        userText1.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        userText1.setText("Designation");

        userText2.setFont(new java.awt.Font("Cochin", 1, 18)); // NOI18N
        userText2.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(userDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userText1)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userType, 0, 170, Short.MAX_VALUE)
                            .addComponent(inputName)
                            .addComponent(inputDistrict)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userText2)
                            .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 367, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(371, 371, 371)
                .addComponent(back)
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userText1)
                            .addComponent(userText2))
                        .addGap(48, 48, 48)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        fillComboBox();
        userText.setVisible(false);
        inputText.setVisible(false);
        userName.setVisible(false);
        inputName.setVisible(false);
        userDistrict.setVisible(false);
        inputDistrict.setVisible(false);
        userText1.setVisible(false);
        userText2.setVisible(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        img.setIcon(new javax.swing.ImageIcon("/Users/vivek/NetBeansProjects/SmartCity/src/main/java/images/update user big.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        jLabel5.setText("Update User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillComboBox()
    {
        Connection con=null;
            PreparedStatement pst2=null;
            ResultSet rs2=null;
            try
            {
                String url="jdbc:mysql://localhost:3306/SmartCity";
                String usern="root";
                String pwd="";
                con=DriverManager.getConnection(url,usern,pwd);
                if(con!=null)
                {
                    String query2="select * from login";
                    pst2=con.prepareStatement(query2);
                    rs2=pst2.executeQuery();
                    while(rs2.next())
                    {
                        String name=rs2.getString("username");
                        userType.addItem(name);
                    }
                }
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        AdminPage adminpage=new AdminPage();
        adminpage.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String uname=inputName.getText();
        String udistrict=inputDistrict.getText();
        String utext=inputText.getText();
        String sname=userType.getSelectedItem().toString();
        String strusertype="";
        Connection con=null;
        PreparedStatement pst=null;
        PreparedStatement pst1=null;
        ResultSet rs=null;
        ResultSet rs1=null;
        try
        {
            String url="jdbc:mysql://localhost:3306/SmartCity";
                String usern="root";
                String pwd="";
                con=DriverManager.getConnection(url,usern,pwd);
                if(con!=null)
                {
                    String query="select * from login where username=?";
                    pst=con.prepareStatement(query);
                    pst.setString(1,uname);
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        strusertype=rs.getString("usertype");
                        if(strusertype.equalsIgnoreCase("principal"))
                        {
                            String query1="update principal set name=?,district=?,school=? where name=?";
                            pst1=con.prepareStatement(query1);
                            pst1.setString(1,uname);
                            pst1.setString(2,udistrict);
                            pst1.setString(3,utext);
                            pst1.setString(4,sname);
                            pst1.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Updated Successfully!");
                            AdminPage adminpage= new AdminPage();
                            adminpage.setVisible(true);
                            dispose();
                        }
                        if(strusertype.equalsIgnoreCase("contractor"))
                        {
                            String query1="update principal set name=?,district=?,company_name=? where name=?";
                            pst1=con.prepareStatement(query1);
                            pst1.setString(1,uname);
                            pst1.setString(2,udistrict);
                            pst1.setString(3,utext);
                            pst1.setString(4,sname);
                            pst1.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Updated Successfully!");
                            AdminPage adminpage= new AdminPage();
                            adminpage.setVisible(true);
                            dispose();
                        }
                        if(strusertype.equalsIgnoreCase("mla"))
                        {
                            String query1="update principal set name=?,district=?,state=? where name=?";
                            pst1=con.prepareStatement(query1);
                            pst1.setString(1,uname);
                            pst1.setString(2,udistrict);
                            pst1.setString(3,utext);
                            pst1.setString(4,sname);
                            pst1.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Updated Successfully!");
                            AdminPage adminpage= new AdminPage();
                            adminpage.setVisible(true);
                            dispose();
                        }
                        if(strusertype.equalsIgnoreCase("cm"))
                        {
                            String query1="update principal set name=?,state=? where name=?";
                            pst1=con.prepareStatement(query1);
                            pst1.setString(1,uname);
                            pst1.setString(2,udistrict);
                            pst1.setString(4,sname);
                            pst1.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Updated Successfully!");
                            AdminPage adminpage= new AdminPage();
                            adminpage.setVisible(true);
                            dispose();
                        }
                    }
                }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void userTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeActionPerformed
        // TODO add your handling code here:
        String uname=userType.getSelectedItem().toString();
        String strusertype="";
        Connection con=null;
            PreparedStatement pst=null;
            PreparedStatement pst1=null;
            PreparedStatement pst3=null;
            ResultSet rs=null;
            ResultSet rs1=null;
        try{
                String url="jdbc:mysql://localhost:3306/SmartCity";
                String usern="root";
                String pwd="";
                con=DriverManager.getConnection(url,usern,pwd);
                if(con!=null)
                {
                    String query="select * from login where username=?";
                    pst=con.prepareStatement(query);
                    pst.setString(1,uname);
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        strusertype=rs.getString("usertype");
                        System.out.println(strusertype);
                        if(strusertype.equalsIgnoreCase("principal"))
                        {
                            String query1="select * from principal where name=?";
                            pst1=con.prepareStatement(query1);
                            pst1.setString(1,uname);
                            rs1=pst1.executeQuery();
                            if(rs1.next())
                            {
                                userName.setVisible(true);
                                inputName.setText(rs1.getString("name"));
                                inputName.setVisible(true);
                                userDistrict.setVisible(true);
                                userText.setVisible(true);
                                inputDistrict.setText(rs1.getString("district"));
                                inputDistrict.setVisible(true);
                                inputText.setText(rs1.getString("school"));
                                inputText.setVisible(true);
                                userText2.setText(strusertype);
                                userText1.setVisible(true);
                                userText2.setVisible(true);
                            }
                        }
                        if(strusertype.equalsIgnoreCase("contractor"))
                        {
                            
                            String query1="select * from contractor where name=?";
                            pst1=con.prepareStatement(query1);
                            pst1.setString(1,uname);
                            rs1=pst1.executeQuery();
                            if(rs1.next())
                            {
                                userName.setVisible(true);
                                inputName.setText(rs1.getString("name"));
                                inputName.setVisible(true);
                                userDistrict.setVisible(true);
                                userText.setVisible(true);
                                userText.setText("Comapny Name");
                                inputDistrict.setText(rs1.getString("district"));
                                inputDistrict.setVisible(true);
                                inputText.setText(rs1.getString("company_name"));
                                inputText.setVisible(true);
                                userText2.setText(strusertype);
                                userText1.setVisible(true);
                                userText2.setVisible(true);
                            }
                        }
                        if(strusertype.equalsIgnoreCase("mla"))
                        {
                            String query1="select * from mla where name=?";
                            pst1=con.prepareStatement(query1);
                            pst1.setString(1,uname);
                            rs1=pst1.executeQuery();
                            if(rs1.next())
                            {
//                                userName.setText(rs.getName("name"));
                                userName.setVisible(true);
                                inputName.setText(rs1.getString("name"));
                                inputName.setVisible(true);
                                userDistrict.setVisible(true);
                                userText.setVisible(true);
                                userText.setText("State");
                                inputDistrict.setText(rs1.getString("district"));
                                inputDistrict.setVisible(true);
                                inputText.setText(rs1.getString("state"));
                                inputText.setVisible(true);
                                userText2.setText(strusertype);
                                userText1.setVisible(true);
                                userText2.setVisible(true);
                            }
                        }
                        if(strusertype.equalsIgnoreCase("cm"))
                        {
                            String query1="select * from cm where name=?";
                            pst1=con.prepareStatement(query1);
                            pst1.setString(1,uname);
                            rs1=pst1.executeQuery();
                            if(rs1.next())
                            {
                                userName.setVisible(true);
                                inputName.setText(rs1.getString("name"));
                                inputName.setVisible(true);
                                userDistrict.setVisible(true);
                                userDistrict.setText("State");
                                inputDistrict.setText(rs1.getString("state"));
                                inputDistrict.setVisible(true);
                                userText.setVisible(false);
                                inputText.setVisible(false);
                                userText2.setText(strusertype);
                                userText1.setVisible(true);
                                userText2.setVisible(true);
                            }
                        }
                    }
                   
                    
                }
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_userTypeActionPerformed

    private void inputDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDistrictActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateUser add=new UpdateUser();
                 add.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel img;
    private javax.swing.JTextField inputDistrict;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputText;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel userDesignation;
    private javax.swing.JLabel userDistrict;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userText;
    private javax.swing.JLabel userText1;
    private javax.swing.JLabel userText2;
    private javax.swing.JComboBox<String> userType;
    // End of variables declaration//GEN-END:variables
}
